import {test} from 'node:test';import assert from 'node:assert/strict';import {handleAdminLogin} from '../admin-auth.mjs';import handler from '../api/app.mjs';import {phoneIdentity} from '../supabase-auth.mjs';
const req=(body,origin='https://emel.test')=>new Request('https://emel.test/api/admin/login',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(body)});
const env={ADMIN_USERNAME:'association-admin',ADMIN_LOGIN_PHONE:'+22244444444'};
const session={access_token:'private-session',refresh_token:'private-refresh',expires_in:3600};
const fake=role=>async(url,opts)=>{const path=new URL(url).pathname;if(path==='/auth/v1/token'){assert.deepEqual(JSON.parse(opts.body),{email:phoneIdentity(env.ADMIN_LOGIN_PHONE),password:'example-password'});return Response.json(session)}if(path==='/auth/v1/user')return Response.json({id:'user-1'});assert.equal(new URL(url).searchParams.get('user_id'),'eq.user-1');return Response.json(role?[{role}]:[])};
test('admin username/password session requires authorized Supabase organization membership',async()=>{let r=await handleAdminLogin(req({username:env.ADMIN_USERNAME,password:'example-password'}),fake('owner'),env);assert.equal(r.status,200);assert.equal(r.headers.getSetCookie().length,2);assert.doesNotMatch(await r.text(),/private-session/);r=await handleAdminLogin(req({username:env.ADMIN_USERNAME,password:'example-password'}),fake(null),env);assert.equal(r.status,403);assert.equal(r.headers.getSetCookie().length,0);});
test('admin rejects wrong usernames and cross-origin requests without contacting auth provider',async()=>{const fetcher=()=>{throw Error('must not contact auth')};let r=await handleAdminLogin(req({username:'wrong',password:'example-password'}),fetcher,env);assert.equal(r.status,401);r=await handleAdminLogin(req({username:env.ADMIN_USERNAME,password:'example-password'},'https://other.test'),fetcher,env);assert.equal(r.status,403);});
test('direct admin pages require staff membership, and login page contains no public signup',async()=>{const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v},end(body){this.body=body}});let r=response();await handler({headers:{host:'emel.test',cookie:'__Host-emel_access=private-session'},url:'/admin',method:'GET'},r,fake(null));assert.equal(r.statusCode,403);assert.doesNotMatch(r.body,/id="sidebar"/);r=response();await handler({headers:{host:'emel.test',cookie:'__Host-emel_access=private-session'},url:'/admin',method:'GET'},r,fake('owner'));assert.equal(r.statusCode,200);assert.match(r.body,/id="sidebar"/);r=response();await handler({headers:{host:'emel.test'},url:'/admin/login',method:'GET'},r);assert.equal(r.statusCode,200);assert.match(r.body,/autocomplete="username"/);assert.doesNotMatch(r.body,/id="registerTab"|\/api\/auth\/register/);});

test('initial administrator provisioning requires the protected initial password and never self-grants staff roles',async()=>{let calls=[];const fetcher=async(url,opts)=>{const path=new URL(url).pathname;calls.push(path);if(path==='/auth/v1/token')return Response.json({error_code:'invalid_credentials'},{status:400});if(path==='/auth/v1/signup')return Response.json(session);if(path==='/auth/v1/user')return Response.json({id:'new-admin'});return Response.json([])};const setupEnv={...env,ADMIN_INITIAL_PASSWORD:'initial-example'};let result=await handleAdminLogin(req({username:env.ADMIN_USERNAME,password:'wrong-password'}),fetcher,setupEnv);assert.equal(result.status,401);assert.deepEqual(calls,['/auth/v1/token']);calls=[];result=await handleAdminLogin(req({username:env.ADMIN_USERNAME,password:'initial-example'}),fetcher,setupEnv);assert.equal(result.status,403);assert.equal((await result.json()).setupRequired,true);assert.ok(calls.includes('/auth/v1/signup'));assert.equal(result.headers.getSetCookie().length,0);});
