import {test} from 'node:test';
import assert from 'node:assert/strict';
import {handleAuth,normalizePhone,phoneIdentity} from '../supabase-auth.mjs';
const session={access_token:'access-example',refresh_token:'refresh-example',expires_in:3600};
const req=(action,body)=>new Request('https://emel.test/api/auth/'+action,{method:'POST',headers:{'content-type':'application/json',origin:'https://emel.test'},body:JSON.stringify(body)});
test('phone signup accepts Arabic digits and uses an internal email identity without SMS, with private session cookies',async()=>{assert.equal(normalizePhone('+٢٢٢ ٤٤٤٤٤٤٤٤'),'+22244444444');assert.throws(()=>normalizePhone('44444444'));let payload;const res=await handleAuth(req('register',{phone:'+22244444444',password:'secret123',email:'ignored@example.test'}),async(url,opts)=>{assert.equal(new URL(url).pathname,'/auth/v1/signup');payload=JSON.parse(opts.body);return Response.json(session)});assert.deepEqual(payload,{email:phoneIdentity('+22244444444'),password:'secret123',data:{login_phone:'+22244444444'}});assert.equal(payload.phone,undefined);assert.deepEqual(await res.json(),{ok:true,authenticated:true});const cookies=res.headers.getSetCookie();assert.equal(cookies.length,2);for(const cookie of cookies)assert.match(cookie,/HttpOnly; Secure; SameSite=Lax; Path=\//);});
test('signup awaiting email configuration does not report a login session',async()=>{const res=await handleAuth(req('register',{phone:'+22244444444',password:'secret123'}),async()=>Response.json({user:{id:'example'}}));assert.equal(res.status,202);assert.equal((await res.json()).authenticated,false);assert.equal(res.headers.getSetCookie().length,0);});
test('invalid password and cross-origin requests are rejected',async()=>{const res=await handleAuth(req('login',{phone:'+22244444444',password:'wrong'}),async()=>Response.json({code:'invalid_credentials'},{status:400}));assert.equal(res.status,400);assert.equal(res.headers.getSetCookie().length,0);const blocked=await handleAuth(new Request('https://emel.test/api/auth/register',{method:'POST',headers:{origin:'https://other.test'}}),()=>{throw Error('must not fetch')});assert.equal(blocked.status,403);});
test('expired access cookie refreshes session instead of logging user out',async()=>{let calls=0;const res=await handleAuth(new Request('https://emel.test/api/auth/session',{headers:{cookie:'__Host-emel_access=expired; __Host-emel_refresh=refresh-example'}}),async(url,opts)=>{calls++;if(calls===1)return Response.json({message:'expired'},{status:401});if(calls===2){assert.equal(new URL(url).searchParams.get('grant_type'),'refresh_token');assert.deepEqual(JSON.parse(opts.body),{refresh_token:'refresh-example'});return Response.json(session);}return Response.json({phone:'22244444444'});});assert.equal(calls,3);assert.equal((await res.json()).authenticated,true);assert.equal(res.headers.getSetCookie().length,2);});

test('login maps the same normalized phone identity and session displays phone metadata',async()=>{const res=await handleAuth(req('login',{phone:'+٢٢٢ ٤٤٤٤٤٤٤٤',password:'secret123'}),async(url,opts)=>{assert.equal(new URL(url).searchParams.get('grant_type'),'password');assert.deepEqual(JSON.parse(opts.body),{email:phoneIdentity('+22244444444'),password:'secret123'});return Response.json(session)});assert.equal(res.status,200);const state=await handleAuth(new Request('https://emel.test/api/auth/session',{headers:{cookie:'__Host-emel_access=access-example'}}),async()=>Response.json({email:phoneIdentity('+22244444444'),user_metadata:{login_phone:'+22244444444'}}));assert.deepEqual(await state.json(),{authenticated:true,phone:'+22244444444'});});

test('Supabase error_code and legacy credential errors produce specific messages without exposing provider payloads',async()=>{for(const payload of [{error_code:'invalid_credentials',msg:'secret provider message'},{error:'invalid_grant',error_description:'Invalid login credentials'}]){const response=await handleAuth(req('login',{phone:'+22244444444',password:'incorrect'}),async()=>Response.json(payload,{status:400}));const body=await response.json();assert.equal(body.code,'invalid_credentials');assert.match(body.error,/إنشاء حساب أولًا/);assert.doesNotMatch(body.error,/secret provider message/);}const response=await handleAuth(req('login',{phone:'+22244444444',password:'incorrect'}),async()=>Response.json({error_code:'email_not_confirmed'},{status:400}));assert.equal((await response.json()).code,'email_not_confirmed');});
