import {test} from 'node:test';import assert from 'node:assert/strict';import {handleSupabase,groupEmail} from '../supabase.mjs';import {handleAdminLogin} from '../admin-auth.mjs';
const user={id:'11111111-2222-3333-4444-555555555555'};
const req=(path,method='GET',body)=>new Request('https://emel.test'+path,{method,headers:{authorization:'Bearer staff',origin:'https://emel.test','content-type':'application/json'},body:body?JSON.stringify(body):undefined});
const staff=(role,extra=()=>null)=>async(url,options)=>{const u=new URL(url);if(u.pathname==='/auth/v1/user')return Response.json(user);if(u.pathname==='/rest/v1/emel_memberships')return Response.json(role?[{role}]:[]);return extra(u,options)||Response.json([])};
test('only the owner manages the three group accounts',async()=>{for(const role of ['editor','viewer',null]){const r=await handleSupabase(req('/api/team'),staff(role,()=>{throw Error('must not reach group functions')}));assert.equal(r.status,403)}
 const r=await handleSupabase(req('/api/team'),staff('owner',u=>u.pathname==='/rest/v1/rpc/emel_group_list'?Response.json([{email:groupEmail('majlis'),role:'editor',active:true}]):null));assert.equal(r.status,200);const {groups}=await r.json();
 assert.deepEqual(groups.map(g=>[g.key,g.active]),[['majlis',true],['lijan',false],['jamiya',false]]);});
test('activating a group creates its account, sets the password and role; only the three groups are accepted',async()=>{const calls=[];const fetcher=staff('owner',(u,o)=>{const b=o.body?JSON.parse(o.body):{};if(u.pathname==='/auth/v1/signup'){calls.push(['signup',b.email]);return Response.json({error_code:'user_already_exists'},{status:422})}if(u.pathname.startsWith('/rest/v1/rpc/')){calls.push([u.pathname.split('/').pop(),b]);return new Response(null,{status:204})}});
 const r=await handleSupabase(req('/api/team/activate','POST',{key:'lijan',password:'Lijan2026',role:'viewer'}),fetcher);assert.equal(r.status,200);
 assert.deepEqual(calls.map(c=>c[0]),['signup','emel_group_set_password','emel_group_activate']);assert.equal(calls[0][1],groupEmail('lijan'));assert.deepEqual(calls[2][1],{p_email:groupEmail('lijan'),p_role:'viewer',p_name:'اللجان المتخصصة'});
 for(const body of [{key:'admin',password:'Lijan2026',role:'viewer'},{key:'lijan',password:'123',role:'viewer'},{key:'lijan',password:'Lijan2026',role:'owner'}]){const bad=await handleSupabase(req('/api/team/activate','POST',body),staff('owner',()=>{throw Error('must not call')}));assert.ok([400,404].includes(bad.status))}});
const login=body=>new Request('https://emel.test/api/admin/login',{method:'POST',headers:{'content-type':'application/json',origin:'https://emel.test'},body:JSON.stringify(body)});
const env={ADMIN_USERNAME:'association-admin',ADMIN_LOGIN_PHONE:'+22244444444'};const session={access_token:'group-session',refresh_token:'group-refresh',expires_in:3600};
test('group users log in with their username; deactivated groups and unknown names are refused',async()=>{const fetcher=role=>async(url,o)=>{const p=new URL(url).pathname;if(p==='/auth/v1/token'){assert.equal(JSON.parse(o.body).email,groupEmail('majlis'));return Response.json(session)}if(p==='/auth/v1/user')return Response.json(user);if(p==='/rest/v1/emel_memberships')return Response.json(role?[{role}]:[]);throw Error('unexpected '+p)};
 let r=await handleAdminLogin(login({username:' Majlis ',password:'Majlis2026'}),fetcher('editor'),env);assert.equal(r.status,200);assert.equal(r.headers.getSetCookie().length,2);assert.doesNotMatch(await r.text(),/group-session/);
 r=await handleAdminLogin(login({username:'majlis',password:'Majlis2026'}),fetcher(null),env);assert.equal(r.status,403);assert.equal(r.headers.getSetCookie().length,0);
 r=await handleAdminLogin(login({username:'someone',password:'x'}),()=>{throw Error('must not contact auth')},env);assert.equal(r.status,401);});
