import {test} from 'node:test';import assert from 'node:assert/strict';import handler from '../api/app.mjs';
const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v},end(text){this.body=text}});
test('frontend opens directly without password or database, without login challenge',async()=>{const old={...process.env};try{delete process.env.ADMIN_PASSWORD;delete process.env.DATABASE_URL;delete process.env.POSTGRES_URL;for(const url of ['/dashboard','/dashboard/','/app?page=dashboard']){const res=response();await handler({headers:{host:'emel.test'},url,method:'GET'},res);assert.equal(res.statusCode,200);assert.match(res.body,/id="sidebar"/);assert.match(res.body,/معاينة الواجهة/);assert.doesNotMatch(res.body,/onclick="logout\(\)"/);assert.equal(res.headers['WWW-Authenticate'],undefined);}}finally{for(const key of ['ADMIN_PASSWORD','DATABASE_URL','POSTGRES_URL']){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key]}}});
test('preview returns no real records even when old backend settings exist, and prevents writes',async()=>{const old=process.env.DATABASE_URL;try{process.env.DATABASE_URL='postgres://unused.test';let res=response();await handler({headers:{host:'emel.test'},url:'/api/app?path=records',method:'GET'},res);assert.deepEqual(JSON.parse(res.body),{records:[],preview:true});res=response();await handler({headers:{host:'emel.test'},url:'/api/app?path=records',method:'POST',body:{kind:'member',data:{name:'example'}}},res);assert.equal(res.statusCode,401);assert.match(res.body,/Supabase/);res=response();await handler({headers:{host:'emel.test'},url:'/api/app?path=audit',method:'GET'},res);assert.deepEqual(JSON.parse(res.body),{results:[],preview:true});}finally{if(old===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=old}});

test('visitor homepage is independent from dashboard and contains working section anchors',async()=>{for(const url of ['/','/visitors','/app?page=visitors']){const res=response();await handler({headers:{host:'emel.test'},url,method:'GET'},res);assert.equal(res.statusCode,200);assert.match(res.body,/نرعى اليوم/);assert.match(res.body,/href="\/dashboard"/);assert.doesNotMatch(res.body,/id="sidebar"/);assert.doesNotMatch(res.body,/__LOGO__|__ICON_/);for(const id of ['about','programs','support','questions'])assert.ok(res.body.includes('id="'+id+'"'));}const res=response();await handler({headers:{host:'emel.test'},url:'/missing-page',method:'GET'},res);assert.equal(res.statusCode,404);});

test('account route offers phone and password without email',async()=>{for(const url of ['/account','/app?page=account']){const res=response();await handler({headers:{host:'emel.test'},url,method:'GET'},res);assert.equal(res.statusCode,200);assert.match(res.body,/type="tel"/);assert.match(res.body,/type="password"/);assert.doesNotMatch(res.body,/type="email"/);}});

test('public membership section is available anonymously and accounts return to public site',async()=>{let res=response();await handler({headers:{host:'emel.test'},url:'/',method:'GET'},res);assert.equal(res.statusCode,200);assert.match(res.body,/id="membership"/);assert.match(res.body,/href="\/account\?mode=register"/);res=response();await handler({headers:{host:'emel.test'},url:'/account',method:'GET'},res);assert.match(res.body,/location.replace\('\/#membership'\)/);assert.doesNotMatch(res.body,/location.replace\('\/dashboard'\)/);});
