import {timingSafeEqual,createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {supabaseConfig,createSupabaseClient} from './supabase.mjs';
import {normalizePhone,phoneIdentity,authRequest,applySession} from './supabase-auth.mjs';
const defaults=JSON.parse(readFileSync(new URL('./admin.config.json',import.meta.url),'utf8'));
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
export async function adminRole(token,fetcher=fetch){const client=createSupabaseClient(supabaseConfig(),token,fetcher);const user=await client.request('/auth/v1/user');if(!user?.id)return null;const rows=await client.request('/rest/v1/emel_memberships?select=role&user_id=eq.'+encodeURIComponent(user.id));return ['owner','editor','viewer'].includes(rows?.[0]?.role)?rows[0].role:null;}
export async function handleAdminLogin(req,fetcher=fetch,env=process.env){if(req.method!=='POST')return json({error:'غير مسموح'},405);const url=new URL(req.url);if(req.headers.get('origin')&&req.headers.get('origin')!==url.origin)return json({error:'طلب غير مسموح'},403);if(!req.headers.get('content-type')?.startsWith('application/json'))return json({error:'طلب غير صالح'},415);try{const body=await req.json();const username=env.ADMIN_USERNAME||defaults.username;if(typeof body.username!=='string'||typeof body.password!=='string'||!body.password||body.password.length>1024)return json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'},401);if(body.username.trim()!==username)return memberLogin(body,fetcher);const phone=env.ADMIN_LOGIN_PHONE||defaults.phone;if(!phone)return json({error:'حساب الإدارة لم يُربط بعد. يلزم تحديد حساب المسؤول ومنحه صلاحية إدارة.'},503);const email=phoneIdentity(normalizePhone(phone));let session;try{session=await authRequest('/auth/v1/token?grant_type=password',{email,password:body.password},fetcher)}catch(error){const secret=env.ADMIN_INITIAL_PASSWORD;const entered=Buffer.from(body.password),expected=Buffer.from(secret||'');if(error.code!=='invalid_credentials'||!secret||entered.length!==expected.length||!timingSafeEqual(entered,expected))throw error;session=await authRequest('/auth/v1/signup',{email,password:body.password,data:{login_phone:normalizePhone(phone)}},fetcher);if(!session.access_token||!session.refresh_token)return json({error:'حساب الإدارة يحتاج تأكيدًا في Supabase. تأكد من تعطيل Confirm email للحسابات الجديدة.'},409);}if(!session.access_token||!session.refresh_token)return json({error:'تعذر بدء جلسة الإدارة'},401);if(!await adminRole(session.access_token,fetcher))return json({error:'تم التحقق من الحساب، لكن صلاحية الإدارة تحتاج تفعيلًا مرة واحدة في Supabase. شغّل أمر التفعيل الذي أرفقته لك ثم أعد الدخول.',setupRequired:true},403);return applySession(json({ok:true}),session);}catch(error){if(error.code==='invalid_credentials')return json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'},401);return json({error:error.message||'تعذر تسجيل الدخول'},error.status||400)}}
const memberPhone=value=>{const raw=String(value||'').replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[\s()-]/g,'').replace(/^00/,'+');if(!/^\+?\d{8,15}$/.test(raw))return null;try{return normalizePhone(/^\d{8}$/.test(raw)?'+222'+raw:raw.startsWith('+')?raw:'+'+raw)}catch{return null}};
async function memberLogin(body,fetcher){const phone=memberPhone(body.username);if(!phone)return json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'},401);
 const code=typeof body.code==='string'?body.code.replace(/\s/g,''):'';if(code&&!/^\d{6}$/.test(code))return json({error:'رمز الدعوة يتكون من 6 أرقام',needCode:true},400);
 const codeHash=code?createHash('sha256').update(code).digest('hex'):'',email=phoneIdentity(phone);
 try{let session;
 try{session=await authRequest('/auth/v1/token?grant_type=password',{email,password:body.password},fetcher)}catch(error){
  if(error.code!=='invalid_credentials')throw error;
  if(!code)return json({error:'رقم الهاتف أو كلمة المرور غير صحيحة. في أول دخول أدخل رمز الدعوة واختر كلمة مرور جديدة.',needCode:true},401);
  const valid=await createSupabaseClient(supabaseConfig(),'',fetcher).request('/rest/v1/rpc/emel_check_invite',{method:'POST',body:JSON.stringify({p_email:email,p_code_hash:codeHash})});
  if(valid!==true)return json({error:'رمز الدعوة غير صحيح أو انتهى. اطلب رمزًا جديدًا من رئيس الجمعية.',needCode:true},401);
  if(body.password.length<6)return json({error:'اختر كلمة مرور من 6 أحرف على الأقل',needCode:true},400);
  try{session=await authRequest('/auth/v1/signup',{email,password:body.password,data:{login_phone:phone}},fetcher)}catch(e){if(e.code==='user_already_exists')return json({error:'لهذا الرقم حساب بكلمة مرور أخرى. أدخل كلمة مرور حسابك مع رمز الدعوة.',needCode:true},401);throw e}
  if(!session.access_token||!session.refresh_token)return json({error:'الحساب يحتاج تأكيدًا في Supabase. تأكد من تعطيل Confirm email.'},409);
 }
 if(!session.access_token||!session.refresh_token)return json({error:'تعذر بدء جلسة الإدارة'},401);
 let role=await adminRole(session.access_token,fetcher);
 if(!role&&code){await createSupabaseClient(supabaseConfig(),session.access_token,fetcher).request('/rest/v1/rpc/emel_claim_invite',{method:'POST',body:JSON.stringify({p_code_hash:codeHash})});role=await adminRole(session.access_token,fetcher)}
 if(!role)return json({error:code?'رمز الدعوة غير صحيح أو انتهى. اطلب رمزًا جديدًا من رئيس الجمعية.':'هذا الحساب غير مفعّل في فريق الإدارة. إن وصلتك دعوة فأدخل رمز الدعوة.',needCode:true},403);
 return applySession(json({ok:true,role}),session);
 }catch(error){if(error.code==='invalid_credentials')return json({error:'رقم الهاتف أو كلمة المرور غير صحيحة'},401);if(error.code==='PGRST202')return json({error:'حسابات فريق الإدارة تحتاج تطبيق db/team.sql في Supabase'},503);return json({error:error.message||'تعذر تسجيل الدخول'},error.status||400)}}
