import {timingSafeEqual} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {supabaseConfig,createSupabaseClient,GROUPS,groupEmail} from './supabase.mjs';
import {normalizePhone,phoneIdentity,authRequest,applySession} from './supabase-auth.mjs';
const defaults=JSON.parse(readFileSync(new URL('./admin.config.json',import.meta.url),'utf8'));
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
export async function adminRole(token,fetcher=fetch){const client=createSupabaseClient(supabaseConfig(),token,fetcher);const user=await client.request('/auth/v1/user');if(!user?.id)return null;const rows=await client.request('/rest/v1/emel_memberships?select=role&user_id=eq.'+encodeURIComponent(user.id));return ['owner','editor','viewer'].includes(rows?.[0]?.role)?rows[0].role:null;}
export async function handleAdminLogin(req,fetcher=fetch,env=process.env){if(req.method!=='POST')return json({error:'غير مسموح'},405);const url=new URL(req.url);if(req.headers.get('origin')&&req.headers.get('origin')!==url.origin)return json({error:'طلب غير مسموح'},403);if(!req.headers.get('content-type')?.startsWith('application/json'))return json({error:'طلب غير صالح'},415);try{const body=await req.json();const username=env.ADMIN_USERNAME||defaults.username;if(typeof body.username!=='string'||typeof body.password!=='string'||!body.password||body.password.length>1024)return json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'},401);if(body.username.trim()!==username)return groupLogin(body,fetcher);const phone=env.ADMIN_LOGIN_PHONE||defaults.phone;if(!phone)return json({error:'حساب الإدارة لم يُربط بعد. يلزم تحديد حساب المسؤول ومنحه صلاحية إدارة.'},503);const email=phoneIdentity(normalizePhone(phone));let session;try{session=await authRequest('/auth/v1/token?grant_type=password',{email,password:body.password},fetcher)}catch(error){const secret=env.ADMIN_INITIAL_PASSWORD;const entered=Buffer.from(body.password),expected=Buffer.from(secret||'');if(error.code!=='invalid_credentials'||!secret||entered.length!==expected.length||!timingSafeEqual(entered,expected))throw error;session=await authRequest('/auth/v1/signup',{email,password:body.password,data:{login_phone:normalizePhone(phone)}},fetcher);if(!session.access_token||!session.refresh_token)return json({error:'حساب الإدارة يحتاج تأكيدًا في Supabase. تأكد من تعطيل Confirm email للحسابات الجديدة.'},409);}if(!session.access_token||!session.refresh_token)return json({error:'تعذر بدء جلسة الإدارة'},401);if(!await adminRole(session.access_token,fetcher))return json({error:'تم التحقق من الحساب، لكن صلاحية الإدارة تحتاج تفعيلًا مرة واحدة في Supabase. شغّل أمر التفعيل الذي أرفقته لك ثم أعد الدخول.',setupRequired:true},403);return applySession(json({ok:true}),session);}catch(error){if(error.code==='invalid_credentials')return json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'},401);return json({error:error.message||'تعذر تسجيل الدخول'},error.status||400)}}
async function groupLogin(body,fetcher){const g=GROUPS.find(x=>x.key===body.username.trim().toLowerCase());if(!g)return json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'},401);
 try{const session=await authRequest('/auth/v1/token?grant_type=password',{email:groupEmail(g.key),password:body.password},fetcher);if(!session.access_token||!session.refresh_token)return json({error:'تعذر بدء جلسة الإدارة'},401);
 if(!await adminRole(session.access_token,fetcher))return json({error:'هذا الحساب موقوف. اطلب من رئيس الجمعية تفعيله.'},403);
 return applySession(json({ok:true}),session);
 }catch(error){if(error.code==='invalid_credentials')return json({error:'اسم المستخدم أو كلمة المرور غير صحيحة'},401);return json({error:error.message||'تعذر تسجيل الدخول'},error.status||400)}}
