import {createHash} from 'node:crypto';
import {supabaseConfig,createSupabaseClient} from './supabase.mjs';
const accessName='__Host-emel_access',refreshName='__Host-emel_refresh';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
export function normalizePhone(value){const phone=String(value||'').replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/[\s()-]/g,'');if(!/^\+[1-9][0-9]{7,14}$/.test(phone))throw Error('أدخل رقم الهاتف مع رمز الدولة، مثل +222 ثم رقمك');return phone;}
export function phoneIdentity(phone){return 'phone-'+createHash('sha256').update(normalizePhone(phone)).digest('hex')+'@accounts.emel6vole.vercel.app';}
function displayPhone(user){return user.user_metadata?.login_phone||user.phone||'';}
export function readCookie(req,name){try{return decodeURIComponent(req.headers.get('cookie')?.split(';').map(c=>c.trim()).find(c=>c.startsWith(name+'='))?.slice(name.length+1)||'')}catch{return ''}}
export function requestAccessToken(req){return req.headers.get('authorization')?.match(/^Bearer (\S+)$/)?.[1]||readCookie(req,accessName);}
export function applySession(response,session){if(!session?.access_token||!session?.refresh_token)throw Error('تعذر بدء الجلسة');const expires=Math.max(1,Math.min(Number(session.expires_in)||3600,86400));response.headers.append('set-cookie',accessName+'='+encodeURIComponent(session.access_token)+'; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age='+expires);response.headers.append('set-cookie',refreshName+'='+encodeURIComponent(session.refresh_token)+'; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000');return response;}
export function clearSession(response){for(const name of [accessName,refreshName])response.headers.append('set-cookie',name+'=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');return response;}
export async function authRequest(path,body,fetcher=fetch){const config=supabaseConfig();let response;try{response=await fetcher(new URL(path,config.url),{method:'POST',headers:{apikey:config.publishableKey,'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});}catch{const error=Error('تعذر الاتصال بخدمة الدخول الآن');error.status=503;throw error;}let data;try{data=await response.json()}catch{data={}}if(!response.ok){const messages={email_provider_disabled:'فعّل مزود Email في Supabase',signup_disabled:'إنشاء الحسابات متوقف في إعدادات Supabase',invalid_credentials:'رقم الهاتف أو كلمة المرور غير صحيحة',email_not_confirmed:'الحساب يحتاج تأكيدًا من صفحة Users في Supabase؛ عطّل Confirm email للحسابات الجديدة',weak_password:'اختر كلمة مرور من 6 أحرف على الأقل',user_already_exists:'رقم الهاتف مرتبط بحساب موجود؛ استخدم تسجيل الدخول',over_request_rate_limit:'محاولات كثيرة، انتظر قليلًا ثم أعد المحاولة',over_sms_send_rate_limit:'تم تجاوز عدد محاولات التسجيل، انتظر قليلًا',sms_send_failed:'المشروع يطلب تأكيد الهاتف برسالة. اضبط إعداد Confirm phone في Supabase حسب طريقة التسجيل المطلوبة'};const error=Error(messages[data.code]||(response.status===429?'محاولات كثيرة، انتظر قليلًا ثم أعد المحاولة':'تعذر تسجيل الدخول أو إنشاء الحساب. تحقق من البيانات وإعدادات Email في Supabase'));error.status=response.status;throw error;}return data;}
export async function refreshSession(req,fetcher=fetch){const refresh=readCookie(req,refreshName);if(!refresh)return null;return authRequest('/auth/v1/token?grant_type=refresh_token',{refresh_token:refresh},fetcher);}
export async function handleAuth(req,fetcher=fetch){const url=new URL(req.url);if(req.method!=='GET'&&req.headers.get('origin')&&req.headers.get('origin')!==url.origin)return json({error:'طلب غير مسموح'},403);
 const action=url.pathname.split('/').pop();
 try{
 if(action==='session'&&req.method==='GET'){let token=requestAccessToken(req),session;if(!token){session=await refreshSession(req,fetcher);token=session?.access_token;}if(!token)return json({authenticated:false});try{const user=await createSupabaseClient(supabaseConfig(),token,fetcher).request('/auth/v1/user');const response=json({authenticated:true,phone:displayPhone(user)});return session?applySession(response,session):response;}catch(e){if(e.status!==401)throw e;if(!session){try{session=await refreshSession(req,fetcher);if(session?.access_token){const user=await createSupabaseClient(supabaseConfig(),session.access_token,fetcher).request('/auth/v1/user');return applySession(json({authenticated:true,phone:displayPhone(user)}),session);}}catch(error){if(error.status!==400&&error.status!==401)throw error;}}return clearSession(json({authenticated:false}));}}
 if(action==='logout'&&req.method==='POST'){const token=requestAccessToken(req);if(token){try{await createSupabaseClient(supabaseConfig(),token,fetcher).request('/auth/v1/logout?scope=local',{method:'POST',body:'{}'})}catch{}}return clearSession(json({ok:true}));}
 if(!['login','register'].includes(action))return json({error:'غير موجود'},404);if(req.method!=='POST')return json({error:'غير مسموح'},405);if(!req.headers.get('content-type')?.startsWith('application/json'))return json({error:'طلب غير صالح'},415);
 const input=await req.json();const phone=normalizePhone(input.phone);if(typeof input.password!=='string'||!input.password||input.password.length>1024)return json({error:'أدخل كلمة مرور صالحة'},400);if(action==='register'&&input.password.length<6)return json({error:'اختر كلمة مرور من 6 أحرف على الأقل'},400);
 const session=await authRequest(action==='register'?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{email:phoneIdentity(phone),password:input.password,...(action==='register'?{data:{login_phone:phone}}:{})},fetcher);
 if(!session.access_token||!session.refresh_token){if(action==='register')return json({ok:true,authenticated:false,confirmationRequired:true,message:'لم تبدأ جلسة الدخول لأن تأكيد البريد مفعّل في Supabase. عطّل Confirm email من إعدادات Authentication ثم أعد المحاولة. الحسابات التي أنشئت قبل تعطيله قد تحتاج تأكيدًا يدويًا من صفحة Users.'},202);return json({error:'تعذر بدء جلسة الدخول'},502);}
 return applySession(json({ok:true,authenticated:true}),session);
 }catch(e){return json({error:e.message||'تعذر تنفيذ الطلب'},e.status||400)}
}
