import {readFileSync} from 'node:fs';import {validate} from './core.mjs';
const defaults=JSON.parse(readFileSync(new URL('./supabase.config.json',import.meta.url),'utf8'));
const prefix={income:'REV',expense:'EXP',member:'MEM',worker:'WRK',beneficiary:'BEN',aid:'AID',settings:'SET'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
export function supabaseConfig(env=process.env){return {url:env.SUPABASE_URL||defaults.url,publishableKey:env.SUPABASE_PUBLISHABLE_KEY||defaults.publishableKey};}
export function createSupabaseClient(config=supabaseConfig(),accessToken='',fetcher=fetch){
 const origin=new URL(config.url);if(origin.protocol!=='https:'||!origin.hostname.endsWith('.supabase.co'))throw Error('عنوان Supabase غير صالح');
 return {async request(path,options={}){const headers={apikey:config.publishableKey,'content-type':'application/json',...options.headers};if(accessToken)headers.Authorization='Bearer '+accessToken;let response;try{response=await fetcher(new URL(path,origin),{...options,headers,signal:AbortSignal.timeout(15000)});}catch{const e=Error('تعذر الاتصال بمشروع Supabase الآن');e.status=503;throw e;}let data=null;const text=await response.text();if(text){try{data=JSON.parse(text)}catch{data=null;}}
 if(!response.ok){const e=Error(['42P01','PGRST205'].includes(data?.code)?'جداول الجمعية لم تُجهز في Supabase بعد':response.status===401?'جلسة Supabase غير صالحة أو منتهية':response.status===403?'لا توجد صلاحية للوصول إلى سجلات الجمعية':data?.code==='P0001'?'تعذر حفظ السجل: تحقق من بيانات الحالة وارتباط المساعدات بها':'تعذر تنفيذ العملية في Supabase');e.status=['42P01','PGRST205'].includes(data?.code)?503:response.status;throw e;}return data;
 }};
}
export async function supabaseStatus(fetcher=fetch){try{await createSupabaseClient(supabaseConfig(),'',fetcher).request('/rest/v1/');return json({configured:true,reachable:true,projectHost:new URL(supabaseConfig().url).hostname});}catch(e){return json({configured:true,reachable:false,error:e.message},e.status||503)}}
export async function handleSupabase(req,fetcher=fetch){const url=new URL(req.url);const origin=req.headers.get('origin');if(req.method!=='GET'&&origin&&origin!==url.origin)return json({error:'طلب غير مسموح'},403);
 const token=req.headers.get('authorization')?.match(/^Bearer (\S+)$/)?.[1];if(!token){if(req.method==='GET'&&url.pathname==='/api/records')return json({records:[],preview:true});if(req.method==='GET'&&url.pathname==='/api/audit')return json({results:[],preview:true});return json({error:'هذه معاينة للواجهة. حفظ بيانات فعلية يحتاج جلسة Supabase لحساب مصرح له.'},401);}
 try{
 const client=createSupabaseClient(supabaseConfig(),token,fetcher);const user=await client.request('/auth/v1/user');if(!user?.id)return json({error:'جلسة غير صالحة'},401);
 const members=await client.request('/rest/v1/emel_memberships?select=role&user_id=eq.'+encodeURIComponent(user.id));const role=members?.[0]?.role;if(!role)return json({error:'الحساب غير مصرح له بالوصول إلى سجلات الجمعية'},403);
 if(url.pathname==='/api/records'&&req.method==='GET'){const rows=[];for(let offset=0;offset<100000;offset+=1000){const chunk=await client.request('/rest/v1/emel_records?select=id,kind,payload&deleted=eq.false&order=id.desc&limit=1000&offset='+offset);rows.push(...chunk);if(chunk.length<1000)return json({records:rows.map(r=>({...r.payload,id:r.id,kind:r.kind,code:prefix[r.kind]+'-'+String(r.id).padStart(6,'0')})),preview:false});}return json({error:'عدد السجلات كبير جدًا للعرض دفعة واحدة'},503);}
 if(url.pathname==='/api/audit'&&req.method==='GET'){const rows=await client.request('/rest/v1/emel_audit?select=id,record_id,action,created_at&order=id.desc&limit=100');return json({results:rows.map(r=>({...r,at:r.created_at}))});}
 const match=url.pathname.match(/^\/api\/records(?:\/(\d+))?$/);if(!match)return json({error:'غير موجود'},404);if(!['POST','PUT','DELETE'].includes(req.method))return json({error:'غير مسموح'},405);if(!['owner','editor'].includes(role))return json({error:'الحساب يملك صلاحية الاطلاع فقط'},403);
 const id=match[1]?Number(match[1]):null;if(id&&!Number.isSafeInteger(id))return json({error:'رقم السجل غير صالح'},400);let previous;if(id){previous=(await client.request('/rest/v1/emel_records?select=id,kind,payload&deleted=eq.false&id=eq.'+id))[0];if(!previous)return json({error:'السجل غير موجود'},404);}
 if(req.method==='DELETE'){if(!id)return json({error:'حدد السجل المطلوب'},400);await client.request('/rest/v1/emel_records?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({deleted:true})});return json({ok:true});}
 if((req.method==='PUT'&&!id)||(req.method==='POST'&&id))return json({error:'طلب غير صالح'},400);
 const input=await req.json();const kind=previous?.kind||input.kind;let payload;try{payload=validate(kind,input.data);}catch(e){return json({error:e.message},400)}delete payload.id;delete payload.kind;delete payload.code;const beneficiaryId=kind==='aid'?Number(payload.beneficiaryId):null;if(kind==='aid'){if(!Number.isSafeInteger(beneficiaryId)||beneficiaryId<1)return json({error:'رقم المستفيد غير صالح'},400);payload.beneficiaryId=beneficiaryId;}
 const body=id?{payload,beneficiary_id:beneficiaryId}:{kind,payload,beneficiary_id:beneficiaryId};const rows=await client.request('/rest/v1/emel_records'+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});if(!rows?.[0])return json({error:'تعذر حفظ السجل'},409);return json({ok:true,id:rows[0].id},id?200:201);
 }catch(e){return json({error:e.message||'تعذر الوصول إلى قاعدة البيانات'},e.status||503)}
}
