-- Apply once through Supabase SQL Editor or the connected Supabase tool.
-- Anonymous visitors cannot access association records.
BEGIN;
CREATE TABLE IF NOT EXISTS public.emel_memberships (
 user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
 role text NOT NULL CHECK (role IN ('owner','editor','viewer'))
);
CREATE TABLE IF NOT EXISTS public.emel_records (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 kind text NOT NULL CHECK (kind IN ('income','expense','member','worker','beneficiary','aid','settings','patient','child','stock')),
 payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
 beneficiary_id bigint REFERENCES public.emel_records(id) ON DELETE RESTRICT,
 deleted boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK ((kind = 'aid' AND beneficiary_id IS NOT NULL) OR (kind <> 'aid' AND beneficiary_id IS NULL))
);
CREATE INDEX IF NOT EXISTS emel_active_aid_beneficiary ON public.emel_records(beneficiary_id) WHERE kind = 'aid' AND NOT deleted;
CREATE TABLE IF NOT EXISTS public.emel_audit (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 record_id bigint NOT NULL,
 action text NOT NULL CHECK (action IN ('create','update','delete')),
 before_data jsonb,
 after_data jsonb,
 actor_id uuid,
 created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.emel_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emel_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emel_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.emel_memberships, public.emel_records, public.emel_audit FROM anon, authenticated;
GRANT SELECT ON public.emel_memberships TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.emel_records TO authenticated;
GRANT SELECT ON public.emel_audit TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.emel_records_id_seq TO authenticated;
DROP POLICY IF EXISTS emel_self_membership ON public.emel_memberships;
CREATE POLICY emel_self_membership ON public.emel_memberships FOR SELECT TO authenticated USING (user_id = auth.uid());
DROP POLICY IF EXISTS emel_read_records ON public.emel_records;
CREATE POLICY emel_read_records ON public.emel_records FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.emel_memberships WHERE user_id = auth.uid()));
DROP POLICY IF EXISTS emel_create_records ON public.emel_records;
CREATE POLICY emel_create_records ON public.emel_records FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.emel_memberships WHERE user_id = auth.uid() AND role IN ('owner','editor')));
DROP POLICY IF EXISTS emel_update_records ON public.emel_records;
CREATE POLICY emel_update_records ON public.emel_records FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.emel_memberships WHERE user_id = auth.uid() AND role IN ('owner','editor'))) WITH CHECK (EXISTS (SELECT 1 FROM public.emel_memberships WHERE user_id = auth.uid() AND role IN ('owner','editor')));
DROP POLICY IF EXISTS emel_read_audit ON public.emel_audit;
CREATE POLICY emel_read_audit ON public.emel_audit FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.emel_memberships WHERE user_id = auth.uid()));
CREATE OR REPLACE FUNCTION public.emel_validate_record() RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE parent_kind text; parent_deleted boolean;
BEGIN
 IF TG_OP = 'UPDATE' AND (NEW.id <> OLD.id OR NEW.kind <> OLD.kind OR NEW.created_at <> OLD.created_at) THEN RAISE EXCEPTION 'Record identity is immutable'; END IF;
 IF TG_OP = 'INSERT' THEN NEW.created_at := now(); NEW.deleted := false; END IF;
 NEW.updated_at := now();
 NEW.payload := NEW.payload - 'id' - 'kind' - 'code';
 IF octet_length(NEW.payload::text) > 120000 THEN RAISE EXCEPTION 'Record payload is too large'; END IF;
 IF NEW.kind IN ('member','worker','beneficiary','patient','child') AND coalesce(trim(NEW.payload->>'name'),'') = '' THEN RAISE EXCEPTION 'Name is required'; END IF;
 IF NEW.kind = 'stock' AND (coalesce(trim(NEW.payload->>'item'),'') = '' OR coalesce(NEW.payload->>'quantity','') !~ '^\d+(\.\d+)?$' OR (NEW.payload->>'quantity')::numeric <= 0) THEN RAISE EXCEPTION 'Stock item and quantity are required'; END IF;
 IF NEW.kind IN ('income','expense','aid') THEN
  IF coalesce(NEW.payload->>'date','') !~ '^\d{4}-\d{2}-\d{2}$' THEN RAISE EXCEPTION 'Invalid financial date'; END IF;
  PERFORM (NEW.payload->>'date')::date;
  IF coalesce(NEW.payload->>'amount','') !~ '^\d+(\.\d+)?$' OR (NEW.payload->>'amount')::numeric <= 0 THEN RAISE EXCEPTION 'Invalid amount'; END IF;
 END IF;
 IF NEW.kind = 'aid' THEN
  SELECT kind,deleted INTO parent_kind,parent_deleted FROM public.emel_records WHERE id = NEW.beneficiary_id FOR UPDATE;
  IF parent_kind IS DISTINCT FROM 'beneficiary' OR parent_deleted OR (NEW.payload->>'beneficiaryId') IS DISTINCT FROM NEW.beneficiary_id::text THEN RAISE EXCEPTION 'Beneficiary is missing or inactive'; END IF;
 END IF;
 IF TG_OP = 'UPDATE' AND NEW.deleted AND NOT OLD.deleted AND OLD.kind = 'beneficiary' AND EXISTS (SELECT 1 FROM public.emel_records WHERE beneficiary_id = OLD.id AND NOT deleted) THEN RAISE EXCEPTION 'Beneficiary has recorded assistance'; END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS emel_validate_record ON public.emel_records;
CREATE TRIGGER emel_validate_record BEFORE INSERT OR UPDATE ON public.emel_records FOR EACH ROW EXECUTE FUNCTION public.emel_validate_record();
CREATE OR REPLACE FUNCTION public.emel_audit_record() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
BEGIN
 INSERT INTO public.emel_audit(record_id,action,before_data,after_data,actor_id)
 VALUES (NEW.id,CASE WHEN TG_OP = 'INSERT' THEN 'create' WHEN NEW.deleted AND NOT OLD.deleted THEN 'delete' ELSE 'update' END,CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.payload END,NEW.payload,auth.uid());
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.emel_audit_record() FROM PUBLIC;
DROP TRIGGER IF EXISTS emel_audit_record ON public.emel_records;
CREATE TRIGGER emel_audit_record AFTER INSERT OR UPDATE ON public.emel_records FOR EACH ROW EXECUTE FUNCTION public.emel_audit_record();
COMMIT;
-- After creating a user in Supabase Authentication, grant access through SQL:
-- INSERT INTO public.emel_memberships(user_id,role) VALUES ('USER_UUID_FROM_AUTH','owner');
-- No self-registration of organization membership is permitted.
