CREATE TABLE IF NOT EXISTS records (
 id BIGSERIAL PRIMARY KEY,
 kind TEXT NOT NULL,
 payload TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL,
 deleted INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS audit (
 id BIGSERIAL PRIMARY KEY,
 record_id BIGINT NOT NULL,
 action TEXT NOT NULL,
 before TEXT,
 after TEXT,
 at TIMESTAMPTZ NOT NULL
);
