import {readFile,mkdir,writeFile,cp,rm} from 'node:fs/promises';
const output='.vercel/output';const func=output+'/functions/app.func';
await rm(output,{recursive:true,force:true});
await mkdir(func+'/api',{recursive:true});await mkdir(func+'/public',{recursive:true});
await cp('api/app.mjs',func+'/api/app.mjs');await cp('public/index.html',func+'/public/index.html');await cp('public/visitors.html',func+'/public/visitors.html');
await writeFile(func+'/package.json',JSON.stringify({type:'module'}));
await writeFile(func+'/index.mjs','export { default } from "./api/app.mjs";\n');
await writeFile(func+'/.vc-config.json',JSON.stringify({runtime:'nodejs24.x',handler:'index.mjs',launcherType:'Nodejs',shouldAddHelpers:true},null,2));
await writeFile(output+'/config.json',JSON.stringify({version:3,routes:[{src:'^/api/(.*)$',dest:'/app?path=$1'},{src:'^/.*$',dest:'/app'}]},null,2));
console.log('Vercel application function and routes built');
